---
- name: stop sendmail
  service:
    name: sendmail
    state: stopped

- name: disable sendmail
  template:
    src: sendmail.j2
    dest: /etc/rc.conf.d/sendmail

- name: install packages
  with_items: "{{ common_packages }}"
  pkgng:
    name: "{{ item.name }}"

- name: create certs dir
  file:
    path: /etc/ssl/certs
    state: directory

- name: create private certs dir
  file:
    path: /etc/ssl/private
    mode: 0700
    state: directory

- stat: path=/usr/home/devel
  register: devel_home

- name: configure development locale
  template:
    src: login_conf.j2
    dest: /usr/home/devel/.login_conf
  when: devel_home.stat.exists == True

- name: configure cshrc
  template:
    src: cshrc.j2
    dest: /usr/home/devel/.cshrc
  when: devel_home.stat.exists == True
